plugins: ["jekyll-scholar", "jekyll-pandoc"]

markdown: Pandoc

scholar:
  style: css/custom.csl
  bibliography_template: bib

exclude: ["README.md", "jekgit.sh"]
include: [".nojekyll"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
