plugins: ["jekyll-scholar"]

markdown: kramdown
highlighter: rouge

scholar:
    style: css/custom.csl
    bibliography_template: bib

exclude: ["README.md", "jekgit.sh"]
include: [".nojekyll"]

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
