plugins: 
    - "jekyll-scholar"
    - "jekyll-pandoc"

markdown: Pandoc

pandoc:
    extensions:
        - mathjax
        
highlighter: rouge

scholar:
    style: css/custom.csl
    locale: css/locales-en-US.csl
    bibliography_template: bib

exclude: ["README.md", "jekgit.sh"]
include: [".nojekyll"]

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
